# Copyright 2015 Open Platform for NFV Project, Inc. and its contributors
# This software is distributed under the terms and conditions of the 'Apache-2.0'
# license which can be found in the file 'LICENSE' in this package distribution
# or at 'http://www.apache.org/licenses/LICENSE-2.0'.


import logging
import random

logger = logging.getLogger("moon.utilities.misc")


def get_random_name():
    _list = (
        "windy",
        "vengeful",
        "precious",
        "vivacious",
        "quiet",
        "confused",
        "exultant",
        "impossible",
        "thick",
        "obsolete",
        "piquant",
        "fanatical",
        "tame",
        "perfect",
        "animated",
        "dark",
        "stimulating",
        "drunk",
        "depressed",
        "fumbling",
        "like",
        "undesirable",
        "spurious",
        "subsequent",
        "spiteful",
        "last",
        "stale",
        "hulking",
        "giddy",
        "minor",
        "careful",
        "possessive",
        "gullible",
        "fragile",
        "divergent",
        "ill-informed",
        "false",
        "jumpy",
        "damaged",
        "likeable",
        "volatile",
        "handsomely",
        "wet",
        "long-term",
        "pretty",
        "taboo",
        "normal",
        "magnificent",
        "nutty",
        "puzzling",
        "small",
        "kind",
        "devilish",
        "chubby",
        "paltry",
        "cultured",
        "old",
        "defective",
        "hanging",
        "innocent",
        "jagged",
        "economic",
        "good",
        "sulky",
        "real",
        "bent",
        "shut",
        "furry",
        "terrific",
        "hollow",
        "terrible",
        "mammoth",
        "pleasant",
        "scared",
        "obnoxious",
        "absorbing",
        "imported",
        "infamous",
        "grieving",
        "ill-fated",
        "mighty",
        "handy",
        "comfortable",
        "astonishing",
        "brown",
        "assorted",
        "wrong",
        "unsightly",
        "spooky",
        "delightful",
        "acid",
        "inconclusive",
        "mere",
        "careless",
        "historical",
        "flashy",
        "squealing",
        "quarrelsome",
        "empty",
        "long",
    )
    return random.choice(_list)
