version: '3.1'

services:
  jenkins:
    build:
      context: .
    image: blueocean:v0.4
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - jenkins_user=${JENKINS_USER}
      - jenkins_password=${JENKINS_PASSWORD}
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  jenkins-data: