pipeline {
  agent {
    docker {
      image 'wukongsun/moon_python_unit_test'
      args '-e moon_home=${moon_home}'
    }
  }
  stages {
    stage('Python Unit Test') {
      steps {
        script {
          sh("cd ${moon_home}/tests/python_unit")
          sh("bash run_tests")
        }
      }
    }
    stage('Functional Test') {
      script {
          sh("cd ${moon_home}/tests/functional")
          sh("bash run_tests")
      }
    }
  }
}