apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: moon
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          value: "moon"
        - name: MYSQL_USER
          value: "moon"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password_moon.txt
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password_root.txt
        ports:
        - containerPort: 3306
          name: mysql
#        volumeMounts:
#        - name: mysql-persistent-storage
#          mountPath: /var/lib/mysql
#      volumes:
#      - name: mysql-persistent-storage
#        persistentVolumeClaim:
#          claimName: mysql-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  namespace: moon
  name: db
spec:
  ports:
    - port: 3306
  selector:
    app: db
---