apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: manager
  namespace: moon
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: manager
    spec:
      hostname: manager
      containers:
      - name: manager
        image: moonplatform/moon_manager:latest
        ports:
        - containerPort: 8082
---

apiVersion: v1
kind: Service
metadata:
  name: manager
  namespace: moon
spec:
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30001
  selector:
    app: manager
  type: NodePort
