apiVersion: batch/v1
kind: Job
metadata:
  name: functest
  namespace: moon
spec:
  template:
    metadata:
      name: functest
    spec:
      containers:
      - name: functest
        image: moonplatform/moon_python_func_test:latest
        volumeMounts:
        - name: config-volume
          mountPath: /etc/moon
        - name: tests-volume
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: moon-config
      - name: tests-volume
        hostPath:
          path: "{{PATH}}"
      restartPolicy: Never
      #backoffLimit: 4
