apiVersion: batch/v1
kind: Job
metadata:
  name: moonforming
  namespace: moon
spec:
  template:
    metadata:
      name: moonforming
    spec:
      containers:
      - name: moonforming
        image: asteroide/moonforming:v1.3
        env:
        - name: POPULATE_ARGS
          value: "--verbose" # debug mode: --debug
        volumeMounts:
        - name: config-volume
          mountPath: /etc/moon
      volumes:
      - name: config-volume
        configMap:
          name: moon-config
      restartPolicy: Never
      #backoffLimit: 4